### ISSUE TITLE
API殴るマン

### ISSUE THREAD

**Issue by ucpr** [nitoc-ict/daizu-online-judge-client#5]

**Comment by ucpr** [comment]
データを取ってくるところとかAPI殴らないといけないんだけど、そこ自分が実装しようかな的な気持ちでいますが @10riridk0 パイセンやりたかったりしますかー？

**Comment by 10riridk0** [comment]
> データを取ってくるところとかAPI殴らないといけないんだけど、そこ自分が実装しようかな的な気持ちでいますが @10riridk0 パイセンやりたかったりしますかー？

やりたい気持ちはあるんですけど、Vueと仲良くなるので精一杯な気がするので厳しいかもしれないです><!

**Comment by ucpr** [comment]
了解です！じゃあそこは自分が実装しますね〜〜〜〜〜〜〜〜

**Comment by ucpr** [comment]
loginしたらtokenが帰ってくるので、localstorageに突っ込む

**Comment by ucpr** [comment]
`Authorization: Bearer トークン`
